In [5]:
#Dataframe Accessing Methods and Loops
import pandas as pd
rt=pd.read_csv(r"C:\Users\Student\Desktop\KHUSHI\DATA.csv")
print(rt)

data={
    "Name":["A","B"],
    "Age":[24,27],
    "City":["Delhi","Mumbai"]
}
print("\n")
df=pd.DataFrame(data)
print(df)

print("\n")
for index, row in df.iterrows():
    print(row["Name"],row["Age"])

print("\n")
print(rt['MARKS'])

print("\n")
print(rt.isnull())

print("\n")
print(rt.fillna("50%"))

print("\n")
print(rt.dropna())

print("\n")
rt['MARKS']=[80,90,95]
print(rt)

print("\n")
rt.drop("NAME", axis=1, inplace=True)
print(rt)

  NAME  AGE  MARKS
0    A   19   85.0
1    B   25    NaN
2    C   37   69.0


  Name  Age    City
0    A   24   Delhi
1    B   27  Mumbai


A 24
B 27


0    85.0
1     NaN
2    69.0
Name: MARKS, dtype: float64


    NAME    AGE  MARKS
0  False  False  False
1  False  False   True
2  False  False  False


  NAME  AGE MARKS
0    A   19  85.0
1    B   25   50%
2    C   37  69.0


  NAME  AGE  MARKS
0    A   19   85.0
2    C   37   69.0


  NAME  AGE  MARKS
0    A   19     80
1    B   25     90
2    C   37     95


   AGE  MARKS
0   19     80
1   25     90
2   37     95